### ISSUE TITLE
[SUGGESTION] Merge with main program.

### ISSUE THREAD

**Issue by afterdelight** [11philip22/twitter_media_downloader#1]
Why didn't you do a pull request with twint? I requested the same feature on twint's open issue,
https://github.com/twintproject/twint/issues/523
The dev is already working on it.

**Comment by 11philip22** [comment]
Hi Afterdelight, Thanks for your suggestion. I would like to send a merge request but i'm  quite unsure how to proceed. Since this is not a fork and i'm also new to using git in a team/group context. Do you have any ideas how i should go about this?
Cheers,
Philip

**Comment by pielco11** [comment]
@11philip22 in my opinion it would be better to create a new repo in the Twint project org (like `twint_utils`) and place there a class which accepts `twint.output.tweets_list` as argument, and then it extracts the URLs of the photos/videos to download them

You have just to delete some code, basically

How does that sound?

PS: since this repo is your, you'd be added to the project as member and get all credits for this (obv)

**Comment by afterdelight** [comment]
There you go, the solution :)

**Comment by 11philip22** [comment]
@pielco11 Sound like a great plan. Should we exchange contact info or something?

**Comment by afterdelight** [comment]
@11philip22 I think you should discuss it together at https://github.com/twintproject/twint/issues/523. I don't think he saw this message's notification.

**Comment by pielco11** [comment]
Yep, missed the messages. @11philip22 I'm going to add you as member

**Comment by pielco11** [comment]
Added you as member
